- hosts: "{{ FS_MOUNTPOINT }}"
  become: true
  become_user: root
  tasks:
  
    - name: Install Ganglia dependencies
      apt:
        name:
          - autoconf
          - automake
          - libapr1-dev
          - libconfuse-dev
          - pkg-config
          - libpcre3
          - libpcre3-dev
          - libexpat1-dev
          - build-essential
          - zlib1g-dev
        state: present
      tags:
        - ganglia
        - ganglia-monitor

    
    - name: Download Ganglia source code
      get_url:
        url: http://sourceforge.net/projects/ganglia/files/ganglia%20monitoring%20core/3.7.2/ganglia-3.7.2.tar.gz
        dest: /usr/local
      tags:
        - ganglia
        - ganglia-monitor
    
    - name: Extract Ganglia source code
      unarchive:
        src: /usr/local/ganglia-3.7.2.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: rename ganglia
      shell: |
        cd /usr/local && mv ganglia-3.7.2 ganglia

    - name: Compile and install Ganglia
      shell: |
        cd /usr/local/ganglia
        ./configure --prefix=/usr
        make
        make install

    - name: Create gmond.conf
      shell: |
        gmond -t > /usr/local/ganglia/gmond.conf
      tags:
        - ganglia
        - ganglia-monitor

    - name: Change gmond config on client side
      shell: |
        sed -i '18s/  # override_hostname = "mywebserver.domain.com"/override_hostname = "{{ FS_MOUNTPOINT }}"/' /usr/local/ganglia/gmond.conf
        sed -i '21s/send_metadata_interval = 0 \/\*secs \*\//send_metadata_interval = 30 \/\*secs \*\//'  /usr/local/ganglia/gmond.conf
        sed -i '50s/mcast_join = 239.2.11.71/host = 34.126.123.165/'  /usr/local/ganglia/gmond.conf
        sed -i '51s/port = 8649/port = {{ PORT }}/'  /usr/local/ganglia/gmond.conf
        sed -i '56s/udp_recv_channel {/#udp_recv_channel {/'  /usr/local/ganglia/gmond.conf
        sed -i '57s/mcast_join = 239.2.11.71/#mcast_join = 239.2.11.71/'  /usr/local/ganglia/gmond.conf
        sed -i '58s/port = 8649/#port = 8649/'  /usr/local/ganglia/gmond.conf
        sed -i '59s/bind = 239.2.11.71/#bind = 239.2.11.71/'  /usr/local/ganglia/gmond.conf
        sed -i '60s/retry_bind = true/#retry_bind = true/'  /usr/local/ganglia/gmond.conf
        sed -i '64s/}/#}/' /usr/local/ganglia/gmond.conf
        sed -i '68s/tcp_accept_channel/#tcp_accept_channel/'  /usr/local/ganglia/gmond.conf
        sed -i '69s/port = 8649/#port = 8649/'  /usr/local/ganglia/gmond.conf
        sed -i '71s/gzip_output = no/#gzip_output = no/'  /usr/local/ganglia/gmond.conf
        sed -i '72s/}/#}/'  /usr/local/ganglia/gmond.conf
      tags:
        - ganglia
        - ganglia-monitor


    # - name: Start Ganglia monitoring service
    #   service:
    #     name: gmond
    #     state: started

    - name: Restart gmond service and enable after reboot
      ignore_errors: yes
      shell: |
        gmond -c /usr/local/ganglia/gmond.conf
      tags:
        - ganglia
        - ganglia-monitor
